name = "bngold-v2"
main = "worker.js"
compatibility_date = "2024-12-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "bngold-db-v2"
database_id = "2bf8886d-fc31-4486-8671-2b9245587020"

[vars]
APP_ENV = "production"
