name = "bngold-v3"
main = "worker.js"
compatibility_date = "2024-12-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "bngold-db-v4"
database_id = "f5322dad-6577-4557-9669-d91867493778"

[vars]
APP_ENV = "production"
